### ISSUE TITLE
Unable to install plugin 1.7.0 on Elasticsearch 2.1.1 on Ubuntu 14.04 -- ERROR: Could not find plugin descriptor 

### ISSUE THREAD

**Issue by ddieterly** [wikimedia/search-repository-swift#16]
Using latest Elasticsearch.

dek@dek-VirtualBox:~/Downloads/elasticsearch-2.1.1$ curl localhost:9200
{
  "name" : "Rom the Spaceknight",
  "cluster_name" : "elasticsearch",
  "version" : {
    "number" : "2.1.1",
    "build_hash" : "40e2c53a6b6c2972b3d13846e450e66f4375bd71",
    "build_timestamp" : "2015-12-15T13:05:55Z",
    "build_snapshot" : false,
    "lucene_version" : "5.3.1"
  },
  "tagline" : "You Know, for Search"
}

Tried to install on Ubuntu 14.04.

ek@dek-VirtualBox:~/Downloads/elasticsearch-2.1.1$ bin/plugin install org.wikimedia.elasticsearch.swift/swift-repository-plugin/1.7.0
-> Installing org.wikimedia.elasticsearch.swift/swift-repository-plugin/1.7.0...
Trying https://download.elastic.co/org.wikimedia.elasticsearch.swift/swift-repository-plugin/swift-repository-plugin-1.7.0.zip ...
Trying https://search.maven.org/remotecontent?filepath=org/wikimedia/elasticsearch/swift/swift-repository-plugin/1.7.0/swift-repository-plugin-1.7.0.zip ...
Downloading ..............................................................................................................................................................................DONE
Verifying https://search.maven.org/remotecontent?filepath=org/wikimedia/elasticsearch/swift/swift-repository-plugin/1.7.0/swift-repository-plugin-1.7.0.zip checksums if available ...
Downloading .DONE
ERROR: Could not find plugin descriptor 'plugin-descriptor.properties' in plugin zip

Using OpenJDK 1.7.0_91.

dek@dek-VirtualBox:~/Downloads/elasticsearch-2.1.1$ java -version
java version "1.7.0_91"
OpenJDK Runtime Environment (IcedTea 2.6.3) (7u91-2.6.3-0ubuntu0.14.04.1)
OpenJDK 64-Bit Server VM (build 24.91-b01, mixed mode)

**Comment by darshandzend** [comment]
Having the same issue. @ddieterly Did you find any workaround?
