### ISSUE TITLE
bin/plugin -install org.wikimedia.elasticsearch.swift/swift-repository-plugin/<version> does not work

### ISSUE THREAD

**Issue by sajid-raouf** [wikimedia/search-repository-swift#8]
Hi, 

I am not sure what is the problem here, none of the version could be installed (via proxy even).

elasticsearch-1.4.2]# ./bin/plugin -i org.wikimedia.elasticsearch.swift/swift-repository-plugin/0.7 --verbose
-> Installing org.wikimedia.elasticsearch.swift/swift-repository-plugin/0.7...
Trying http://download.elasticsearch.org/org.wikimedia.elasticsearch.swift/swift-repository-plugin/swift-repository-plugin-0.7.zip...
Failed: SocketTimeoutException[connect timed out]
Trying http://search.maven.org/remotecontent?filepath=org/wikimedia/elasticsearch/swift/swift-repository-plugin/0.7/swift-repository-plugin-0.7.zip...
Failed: SocketTimeoutException[connect timed out]
Trying https://oss.sonatype.org/service/local/repositories/releases/content/org/wikimedia/elasticsearch/swift/swift-repository-plugin/0.7/swift-repository-plugin-0.7.zip...
Failed: SocketTimeoutException[connect timed out]
Trying https://github.com/org.wikimedia.elasticsearch.swift/swift-repository-plugin/archive/0.7.zip...
Failed: SocketTimeoutException[connect timed out]
Trying https://github.com/org.wikimedia.elasticsearch.swift/swift-repository-plugin/archive/master.zip...
Failed: SocketTimeoutException[connect timed out]
Failed to install org.wikimedia.elasticsearch.swift/swift-repository-plugin/0.7, reason: failed to download out of all possible locations..., use --verbose to get detailed information

Not sure what is the issue here.

Some help on this would be appreciated.

Best regards,
Abdul Mohammed

**Comment by nomoa** [comment]
Did you fix your issue? Reading the errors I suspect that the box from where you are trying to install the plugin does not have access to internet.

**Comment by sajid-raouf** [comment]
Hi David,
Yes, I already fixed that issue and indeed it was a proxy issue.
Thanks,Abdul
